---
alertmanager_version     : "latest"
alertmanager_port        : 9093
alertmanager_config_dir  : "/data/alertmanager/configs"
alertmanager_data_dir    : "/data/alertmanager/data"
alertmanager_flush       : false
