all:
  children:
    dev:
      hosts:
        dev_workstation:
          ansible_host: 192.168.110.35
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
    jenkins:
      hosts:
        jenkins_server:
          ansible_host: 192.168.110.67
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
    app:
      hosts:
        app_server:
          ansible_host: 192.168.110.74
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
    monitoring:
      hosts:
        monitoring_server:
          ansible_host: 192.168.110.71
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
