all:
  children:
    jenkins:
      hosts:
        jenkins_server:
          ansible_host: 192.168.100.15
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
    app:
      hosts:
        app_server:
          ansible_host: 192.168.100.13
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
    monitoring:
      hosts:
        monitoring_server:
          ansible_host: 192.168.100.14
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
