---
- name: Setup Monitoring and Logging Server
  hosts: monitoring
  become: yes
  roles:
    - prometheus
    - alertmanager
    - grafana
    - node-exporter

- name: Setup Node exporter app
  hosts: app
  become: yes
  roles:
    - node-exporter

- name: Setup Node exporter jenkins
  hosts: jenkins
  become: yes
  roles:
    - node-exporter
