---
# Flush variables for roles
prometheus_flush     : true
alertmanager_flush   : true
grafana_flush        : true
node_exporter_flush  : true
elasticsearch_flush  : true
logstash_flush       : true
kibana_flush         : true
filebeat_flush       : true
jenkins_flush        : true
