---
# Flush variables for roles
prometheus_flush     : false
alertmanager_flush   : false
grafana_flush        : false
node_exporter_flush  : false
elasticsearch_flush  : true
logstash_flush       : true
kibana_flush         : true
filebeat_flush       : true
jenkins_flush        : false
